##########################################################################
# Plugins settings
#
# Status: in use
##########################################################################

core.tools.image-converter.inputFormatExtensions = jpg png gif
core.tools.image-converter.inputFormatMimeTypes = application/jpg application/png application/gif
core.tools.image-converter.inputFormatPronoms = fmt/41 fmt/11 fmt/4 fmt/5
core.tools.image-converter.outputFormats = jpg png gif

core.tools.pronom.fmt/41 = jpg
core.tools.pronom.fmt/11 = png
core.tools.pronom.fmt/4 = gif
core.tools.pronom.fmt/5 = gif

core.plugins.conversion.profile.org.roda.core.plugins.external.ImageConverter = image-converter
core.plugins.conversion.profile.image-converter.profiles.i18nPrefix = image-converter
core.plugins.conversion.profile.image-converter.profiles[] = jpg
core.plugins.conversion.profile.image-converter.profiles[] = png
core.plugins.conversion.profile.image-converter.profiles[] = gif
core.plugins.conversion.profile.image-converter.jpg.canBeUsedForDissemination = true
core.plugins.conversion.profile.image-converter.jpg.canBeUsedForRepresentation = true
core.plugins.conversion.profile.image-converter.png.canBeUsedForDissemination = true
core.plugins.conversion.profile.image-converter.png.canBeUsedForRepresentation = true
core.plugins.conversion.profile.image-converter.gif.canBeUsedForDissemination = true
core.plugins.conversion.profile.image-converter.gif.canBeUsedForRepresentation = true
